image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - package

before_script:
  - chmod +x mvnw

build:
  image: maven:3-jdk-11-openj9
  stage: build
  cache:
    paths:
      - .m2/repository
  tags:
    - TNEsp9-F
  script: ./mvnw package
  artifacts:
    paths:
      - target/*.jar